### ISSUE TITLE
Decision list count

### ISSUE THREAD

**Issue by bennet-esyoil** [crowdsecurity/grafana-dashboards#15]
Hey,

I'd like to display the count of decisions in a graph. 
CAPI and LAPI decisions seperated would be great, is there a metric I can use? 
When I use the Explorer in Grafana I cannot seem to find `cs_lapi_decisions_ko_total` and/or `cs_lapi_decisions_ok_total`

Thanks

**Comment by buixor** [comment]
Hello,

Sorry for the delay and thanks for your investigations.
The [dashboards_v5](https://github.com/crowdsecurity/grafana-dashboards/tree/master/dashboards_v5) contains working dashboards for crowdsec 1.5, testing w/ Grafana 10.0 on Grafana cloud (including decisions counters!).

Please let me know if you face any further issues.
