### ISSUE TITLE
Everything seems broken in Latest Grafana

### ISSUE THREAD

**Issue by sdooweloc** [crowdsecurity/grafana-dashboards#18]
Grafana errors when trying to run these .json's due to not being able to translate legacy queries and find $DS_PROMETHEUS causing the .jsons to be no more useful than a very verbose and difficult to translate how to guide.

**Comment by noodlesup** [comment]
I managed to fix this by manually replacing all occurrences of `${DS_PROMETHEUS}` and `DS_PROMETHEUS ` with `Prometheus` in the dashboards_v4 json files.

Found the solution here : [https://github.com/grafana/grafana/issues/10786#issuecomment-383931147](https://github.com/grafana/grafana/issues/10786#issuecomment-383931147)

I'm using:
  - crowdsecurity/crowdsec:v1.4.6-debian
  - prom/prometheus:v2.43.0
  - grafana/grafana:9.3.6

**Comment by buixor** [comment]
Hello,

Sorry for the delay and thanks for your investigations.
The [dashboards_v5](https://github.com/crowdsecurity/grafana-dashboards/tree/master/dashboards_v5) contains working dashboards for crowdsec 1.5, testing w/ Grafana 10.0 on Grafana cloud (including fixed heatmaps).

Please let me know if you face any further issues.
