### ISSUE TITLE
Insights dashboard not working with fqdn as machine ID

### ISSUE THREAD

**Issue by kresike** [crowdsecurity/grafana-dashboards#20]
Running crowdsec 1.4.6 on multiple machines and using prometheus 2.42.0 to scrape metrics. Using grafana v9.3.6 to display metrics using the dashboards from this repository in directory dashboards_v4.

Everything works as expected except the Crowdsec Insight dashboard which has a problem because of the way I tag my machines.

In the prometheus scrape config I added the machine's FQDN as machine label. This causes the Insight dashboard to escape the dots in the machine id, which in turn causes the panels to display empty values.

```(process_start_time_seconds{machine="XX07\\.XXXX\\.XX"})*1000```

The correct prometheus query should look like this.

```(process_start_time_seconds{machine="XX07.XXXX.XX"})*1000```

My very simple solution was to disable the "Multi value" and "Include all option" in the machine variable in the settings of the Insight dashboard.

**Comment by buixor** [comment]
Hello,

Sorry for the delay and thanks for your investigations.
The [dashboards_v5](https://github.com/crowdsecurity/grafana-dashboards/tree/master/dashboards_v5) contains working dashboards for crowdsec 1.5, testing w/ Grafana 10.0 on Grafana cloud (including fixed heatmaps).

Please let me know if you face any further issues.
