### ISSUE TITLE
The grafana dashboard seems to be broken with latest 1.5.x

### ISSUE THREAD

**Issue by gcheewah** [crowdsecurity/grafana-dashboards#21]
Charts seems to be broken

**Comment by LaurenceJJones** [comment]
Can you give us some more information? any debugging you have conducted? cause saying it broken doesnt give us much information to go on.

EG: your grafana version, promethus version?

**Comment by gcheewah** [comment]
I'm using the grafana cloud.
It seems to be fine now, probably some configuration from my part.
Thanks for replying.
