### ISSUE TITLE
Dashboard's filter on "machine" label doesn't reflect in current data

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/grafana-dashboards#4]
This label doesn't exist in the data pulled by prometheus

**Comment by erenJag** [comment]
This label is set from the [prometheus config](https://github.com/crowdsecurity/grafana-dashboards#prometheus-config), so each target collected will tagged with this label and we use it to do our queries in grafana.

**Comment by erenJag** [comment]
Of course it's now updated and available in the both dashboards version if it wasn't the case.
